mod09ga: mod09ga.c arrays.c
#	gcc -o mod09ga mod09ga.c arrays.c -I/c/msys/local/include   -L/c/msys/local/lib  -llibgdal -lm
	gcc -o mod09ga mod09ga.c arrays.c -I/usr/include/gdal/ -L/usr/lib -lgdal -lm -Wall -fopenmp -Wno-unused-result

clean:
	rm -rf mod09ga
