sam_eta: gdal_sam_eta.c sam_eta.c
#	gcc -o sam_eta gdal_sam_eta.c sam_eta.c -I/c/msys/local/include   -L/c/msys/local/lib  -llibgdal -lm
	gcc -o sam_eta gdal_sam_eta.c sam_eta.c -I/usr/include/gdal/ -L/usr/lib -lgdal1.6.0 -lm -fopenmp -Wall

