extract: gdal_extract.c 
#	gcc -o extract gdal_extract.c -I/c/msys/local/include   -L/c/msys/local/lib  -llibgdal 
	gcc -o extract gdal_extract.c -I/usr/include/gdal/ -L/usr/lib -lgdal -Wall

clean:
	rm -rf extract
