et_pot_d: gdal_et_pot_d.c et_pot_d.c
#	gcc -o eta gdal_eta.c rs.c -I/c/msys/local/include   -L/c/msys/local/lib  -llibgdal -lm
	gcc -o et_pot_d gdal_et_pot_d.c et_pot_d.c -I/usr/include/gdal/ -L/usr/lib -lgdal -lm -fopenmp -Wall


clean:
	rm -rf et_pot_d
