myd09ga: myd09ga.c arrays.c
#	gcc -o myd09ga myd09ga.c arrays.c -I/c/msys/local/include   -L/c/msys/local/lib  -llibgdal -lm
	gcc -o myd09ga myd09ga.c arrays.c -I/usr/include/gdal/ -L/usr/lib -lgdal -lm -Wall -fopenmp -Wno-unused-result

clean:
	rm -rf myd09ga
