g_0: gdal_g0.c g_0.c
#	gcc -o eta gdal_eta.c rs.c -I/c/msys/local/include   -L/c/msys/local/lib  -llibgdal -lm
	gcc -o g_0 gdal_g0.c g_0.c -I/usr/include/gdal/ -L/usr/lib -lgdal -lm -fopenmp -Wall

clean:
	rm -rf g_0
